### ISSUE TITLE
Control PR build through comments

### ISSUE THREAD

**Issue by donny-dont** [harness/harness#2056]
Drone should provide a way to control PR builds through the comment system of the remote.

For example a contributor could specify in the comments to `do: build` and then Drone would kick off a build.

Potential use cases
* Gating a PR build so it is not run until a maintainer approves a run
* Run different configurations such as turning a feature flag on/off

Examples in the wild
* [Jenkins Plugin](https://github.com/jenkinsci/ghprb-plugin)
* [GitLab Integration](https://gitlab.kitware.com/cmake/cmake/merge_requests/798)

**Comment by donny-dont** [comment]
Looking to formalize this into a feature

**Comment by bradrydzewski** [comment]
do you think there should be a formal notation / language similar to `[ci skip]`?

```sh
[drone approve]           # approve the gated build
[drone deploy production] # deploy to production
```

or should we let individual projects define regular expressions or matching criteria in the yaml?

```
triggers:
  - match: deploy to production
    action: deploy
    environment:
      - FOO=bar
      - BAZ=boo
```

in terms of turning feature flags on / off would this be done by injecting environment variables into the build? I included an environment section in the above example for this purpose.

**Comment by mohanraj-r** [comment]
Looking to switch to drone from Jenkins, and this is the feature that is holding me back. 

I guess options for the following would make sense
* auto-build on PR create : boolean
 - auto-build on new commits pushed to PR : boolean 
    - not sure if this needs to be a separate option or rolled in with the PR create option
* auto-merge/close PR on build success: boolean
  - not sure if user config about the remote branch to merge to would be needed for this option
* build-trigger phrase: regex
  - build-trigger user whitelist: list of users who can use the trigger phrase to trigger builds
* PR-merge phrase: regex
  - merge-trigger user whitelist: list of users who can use the trigger phrase to merge PRs

Optionally:
* ability to specify actions after merge (e.g. test and/or build after merge) 
  - But I guess this could be specified as trigger actions on the target branch being merged into?
* I am not sure if it would be useful to have control over status updates from drone on the PR (e.g. control over msg string and customizing using env/build vars).

**Comment by bradrydzewski** [comment]
> auto-build on PR create : boolean
> auto-build on new commits pushed to PR : boolean

fyi drone already does these

**Comment by mohanraj-r** [comment]
Thanks for clarification @bradrydzewski 
Didn't know that drone supports PR triggers - just found http://docs.drone.io/github.html#hooks

> and these can be done via plugins today

Can you post links to the plugins please ?

**Comment by tonglil** [comment]
@mohanraj-r I think he means you can create plugins to do that today; I don't remember seeing any plugins doing that as of today.

**Comment by tonglil** [comment]
@bradrydzewski a common theme here I think is allowing customizable triggers.

A comment is just another event that GH sends to Drone via webhook. 

Looking back at https://github.com/drone/drone/issues/1878#issuecomment-264900509, `Comment created` would cover this.

And if trigger parsing could be customized via plugins, I can see a pipeline definition like this:

```yaml
pipeline:
  test_darwin:
    when:
      - image: plugins/github-comment
        type: create
        contains:
          - test-darwin
          - test-osx

  test_linux:
    when:
      - image: plugins/github-comment
        type: create
        contains: test-linux

  test_windows:
    when:
      - image: plugins/github-comment
        type: create
        contains: test-windows

  # combo of branch and comment
  deploy:
    when:
      - branch: nix/*
      - image: plugins/github-comment
        type: create
        contains:
          - deploy-darwin
          - deploy-osx
          - deploy-linux
```

**Comment by krasi-georgiev** [comment]
@tonglil that looks quite flexible and extensible.
How would the `when` condition decide whether to start the pipeline?
based on the exist code of the plugin? , meaning exit code 0 trigger the build , exit code 1 don't

**Comment by krasi-georgiev** [comment]
aah actually the plugin needs to listen all the time for events so needs to be running all the time.

**Comment by geekdave** [comment]
Use case: Allow PR author (or reviewer) to run a series of more expensive, lengthy tests before merging PR, but not on every single push to the PR.  This could include Selenium tests, integration tests, or even something like standing up a dev cluster with the feature branch changes.

I like how the kubernetes project has a bot that listens to slash-commands, like:

![add_kind_and_version_to_kubeadm_masterconfiguration_configmaps_by_liztio_ _pull_request__63723_ _kubernetes_kubernetes](https://user-images.githubusercontent.com/1438478/39949875-f3f657e4-553a-11e8-8537-c317b849d0c1.jpg)

**Comment by geekdave** [comment]
The kubernetes CI bot also provides a helpful message for PRs from non-org-members and allows trusted members to trigger a test pipeline:

![add_kind_and_version_to_kubeadm_masterconfiguration_configmaps_by_liztio_ _pull_request__63723_ _kubernetes_kubernetes](https://user-images.githubusercontent.com/1438478/39949963-7be5c068-553b-11e8-93db-7bdd7bfe6836.jpg)

**Comment by geekdave** [comment]
Here's the kubernetes CI bot's "vocabulary" which is about much more than just CI - and also includes code review workflow stuff, and CLA validation, etc: https://prow.k8s.io/command-help

More about prow: https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by bradrydzewski** [comment]
@geekdave thanks for the feedback. Would `/test foo` execute only step `foo` or would it execute all pipeline steps including `foo`? If `foo` is the only step executed, is there any concern that artifacts or assets may not existing (e.g. you need to re-download dependencies, re-compile, etc)?

**Comment by ekozan** [comment]
for me /test foo exectute an action on kubernetes 
- Allow test
- Retest

for example : 

```yaml 
pipeline:
  bar:
    image: alpine
    commands: echo hello
    when:
      FULLTEST: TRUE
  baz:
    image: alpine
    commands: echo hello
triggers:
   -match: retest
    action: retest
   -match: ok-to-test
    action: trust_pr
   -match: long test 
    action: retest
    environment:
      - FULLTEST=TRUE
   -match: stop-test
    action: untrust_pr
   -match: deploy
    action: retest
    environment:
      - DEPLOY=TRUE
```
