### ISSUE TITLE
Error "dial tcp 0.0.0.0:4243: connection refused" when running test

### ISSUE THREAD

**Issue by tax** [harness/harness#24]
Thanks for opensourcing this, it is really amazing!

After installing on Ubuntu 12.04 in virtualbox and setting up this repo: https://github.com/tax/testdrone I get the following error when a test is run: 

```
dial tcp 0.0.0.0:4243: connection refused
```

This is my .drone.yml file:

```
image: python:2.7
script:
  - python test.py
notify:
  email:
    recipients:
      - paultax@gmail.com
```

Any idea what might be the problem?
