### ISSUE TITLE
empty secrets on pull_request events

### ISSUE THREAD

**Issue by denislee** [harness/harness#2400]
Hello guys, my drone was working without problem until yesterday, where just stopped retriving secret without any change from my yml file. I'm missing something?

I'm using drone version 0.8.5

```
drone secret add -event pull_request -event push -repository test/test -name sonar_login -value secret

```

```
pipeline:
  test-01:
    image: test/drone-builder
    when: 
      event: pull_request
    commands:
      - echo "$${sonar_login}"
      - echo "$sonar_login"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [sonar_login]
```

```
$ drone secret ls test/test
sonar_login
Events: pull_request, push
Images: <any>

```

```
$ drone repo info test/test
Owner: dns
Repo: test
Type: git
Config: .drone.yml
Visibility: private
Private: true
Trusted: true
Gated: false
Remote: https://github.com/test/test
```

```
$ drone build info test/test 36
Number: 36
Status: success
Event: pull_request
Commit: aec746af425d2a388a5d7ef7a40c231f0cc3f900
Branch: master
Ref: refs/pull/21/merge
Message: fix
Author: dns
```

```
+ echo "${sonar_login}"

+ echo "$sonar_login"

```
