### ISSUE TITLE
RFC: repo status per build step

### ISSUE THREAD

**Issue by jmccann** [harness/harness#2441]
### Summary

This is a proposal to add the ability for every step in a Drone pipeline to be able to create a repo status. Currently only 1 "global" status is created for the entire pipeline (e.g. all steps together).

I feel this could be extremely valuable combined with new ability to allow for a single step not to fail the pipeline (#2071).

### Goals

Here are some goals I envision.  There are details in each goal that could be tweaked, for example naming of things.

* each status would update immediately after a step finishes (not waiting for an entire `group` to finish for example)
* each status would link directly to the logs of that step inside the build
* would be "opt-in", meaning a step would not create a status by default but can be configured to do so from `.drone.yml`
* allow to customize `context` for a step, defaults to `continuous-integration/drone/<step-name>`

### Example Pipeline

```
pipeline:
  # Does not create a status
  restore-cache:
    image: plugins/drone-s3-cache

  # Creates a status with default context
  lint:
    image: node
    group: test
    status: true
    commands:
      - lint command

  # Creates a status with default context
  test:
    image: node
    group: test
    status: true
    commands:
      - test command

  # Does not create a status
  rebuild-cache:
    image: plugins/drone-s3-cache

  # Create a status with custom context
  build:
    image: plugins/docker
    status: continuous-delivery/docker

  # Create a status with custom context
  deploy-test:
    group: deploy
    status: continuous-delivery/k8s/test

  # Create a status with custom context
  deploy-master:
    group: deploy
    status: continuous-delivery/k8s/master
```
