### ISSUE TITLE
Native Docker build and publish support

### ISSUE THREAD

**Issue by bradrydzewski** [harness/harness#2462]
The goal with this change will be to support the `docker build` command natively in Drone. This should help teams that desire to build a Docker image, test inside the Docker image, and then push on success.

__BUILDING:__

The existing docker-compose build syntax would be supported (we are not accepting proposals that deviate from this syntax):

```yaml
steps:
- name: build
  build:
    image: octocat/hello-world
    context: .
```

Example specifies custom dockerfile:

```yaml
steps:
- name: build
  build:
    image: octocat/hello-world
    context: .
    dockerfile: Dockerfile
```

Example demonstrates all available fields (per docker-compose specification):

```yaml
steps:
- name: build
  build:
    content: .
    dockerfile: Dockerfile
    args:
      foo: bar
      baz: boo
    labels:
      foo: bar
      baz: boo
```

It should be possible to build the image, and then use the image in subsequent steps:

```yaml
steps:
- name: build
  build:
    image: octocat/hello-world
    context: .

- name: test
  image: octocat/hello-world
  commands:
  - go build
  - go test
```

__PUBLISHING:__

You optionally have the ability to publish the image at the end of a successful pipeline:

```yaml
steps:
- name: build
  build:
    image: octocat/hello-world
    context: .

- name: test
  image: octocat/hello-world
  commands:
  - go build
  - go test

- name: publish
  image: octocat/hello-world
```

We need to limit when images are published:

```yaml
steps:
- name: publish
  image: octocat/hello-world
  when:
    branch:
    - master
    event:
    - push
    - pull_request
```

__SECURITY:__

The plan is to build on the host machine Docker daemon and to use unique container names (hashes) in place of the tagged names. This will enable the host machine docker cache to reduce build time. This will require us to use the Docker API to push to Dockerhub and push a manifest, so that we can use the original tagged image name, instead of the unique hash.

For example the below image (octocat/hello-world) will be replaced with a unique hash, like ee7fd16f988c7b5156b7de9a1a8cfc10, to prevent it from overwriting tags on the host machine.

```
steps:
- name: build
  build:
    image: octocat/hello-world
    context: .
```

would look like

```
docker build -t ee7fd16f988c7b5156b7de9a1a8cfc10 .
```

__CHALLENGE:__

The main challenge is that I cannot figure out a way to publish and re-tag an image. For example, there is no easy way to do something like this:

```
docker push ee7fd16f988c7b5156b7de9a1a8cfc10 --rename octocat/hello-world
```

It is critical that we never tag an image on the host machine, otherwise a malicious use could (in theory) submit a pull request to overwrite popular images (golang, node, etc) and inject malicious code. __I have no clue how to solve this yet with Docker ...__

I need something like this, but for docker:

```
buildah push imageID docker://registry.example.com/repository:tag
```
