### ISSUE TITLE
secure build config parameters 

### ISSUE THREAD

**Issue by pandemicsyn** [harness/harness#25]
Is what I can put in the repo's secure build params limited to just "key: value" pairs? I wanted to inject:

```
notify:
  email:
    recipients:
      - some@email.com
```

And the UI reports it saved it successfully, but if I navigate away from the page or peek at the repo's sqlite table it doesn't actually persist. Random entries like "somekey: foo" work fine though.
