### ISSUE TITLE
Tag trigger not working

### ISSUE THREAD

**Issue by dbellinghoven** [harness/harness#2558]
I have a Drone cloud instance for my [repo](https://github.com/ddbellinghoven/drone-test). I want it to trigger just one step when it gets a new tag: run unit tests, and build and deploy a new release to the repo's releases page. Here is what my `drone.yml` looks like:

```yaml
---
kind: pipeline
name: build-release

workspace:
  base: /go
  path: src/github.com/ddbellinghoven/drone-test

steps:
- name: build
  image: golang
  commands:
  - go test
  - scripts/build-release.sh

trigger:
  event:
  - tag
```
I based this off of an [example](https://docs.drone.io/user-guide/pipeline/triggers/#by-event) in the docs. It simply does not trigger at all when I push a new tag. When I manually trigger a build, this is the output I see:
![image](https://user-images.githubusercontent.com/25465353/50183892-7415e580-02e1-11e9-89ea-5d2c231f5a03.png)

It appears that it isn't seeing any of the tags at all. However, when I run `git tag` locally, this is the output:
```
v0.0.1
v0.0.10
v0.0.11
v0.0.12
v0.0.13
v0.0.2
v0.0.3
v0.0.4
v0.0.5
v0.0.6
v0.0.7
v0.0.8
v0.0.9
```
 Can anybody help me diagnose this issue?
