### ISSUE TITLE
template converter: template name given not found

### ISSUE THREAD

**Issue by xhatt** [harness/harness#3237]
### I found the same problem as me. [Click Here](https://stackoverflow.com/questions/70622564/drone-template-not-triggering-build)
![微信截图_20220704223044](https://user-images.githubusercontent.com/44392078/177175894-837ae27f-e279-4244-b415-579492db558a.png)

## This is `.drone.yaml`
```yaml
kind: pipeline
type: exec
name: wind
steps:
  - name: build
    commands:
      - docker-compose -p wind_generator build
  - name: start
    commands:
      - docker-compose -p wind_generator up -d
  - name: test_live
    commands:
      - /bin/sh -c "sleep 2;if [ $(curl --noproxy "*" -o /dev/null -s -w %{http_code} -m 5 http://127.0.0.1:5200/liveprobe) = "200" ]; then echo "正常启动"; else echo "服务启动失败" && exit 1 ; fi"

trigger:
  branch:
    - master
  event:
    - push
    - custom

---
kind: template
load: notify.yaml
data:
  depends_on: wind

```

## And this is `notify.yaml`
```yaml
kind: pipeline
type: docker
name: default
clone:
  disable: true

steps:
  - name: email
    image: drillster/drone-email
    settings:
      recipients:
        from_secret: email_recipients
      subject: "Drone build: [{{ build.status }}] {{ repo.name }} ({{ repo.branch }}) #{{ build.number }}"
      host: smtp.qq.com
      port: 465
      from:
        from_secret: email_user
      username:
        from_secret: email_user
      password:
        from_secret: email_password

trigger:
  status: [success, failure]

depends_on: 
  - {{ .input.depends_on }}
```

### You can see from the webpage that my template was successfully created.

![微信截图_20220704223149](https://user-images.githubusercontent.com/44392078/177176926-7565ba4a-d5d0-4111-b8c4-caf995ec9a78.png)

#### I come from China, and the description language may not be so accurate. But I think I should still understand the problem I want to express.
---

### The next day, I found a phenomenon. When I put `.drone.yaml` After the content of yaml is deleted, only one template is retained, like this
```yaml
kind: template
load: notify.yaml
data:
  depends_on: wind
```
