### ISSUE TITLE
Customize triggers or condition according to branches

### ISSUE THREAD

**Issue by Bruc3Stark** [harness/harness#3254]
Hey, I wonder if drone can support customize triggers or condition according to different branches. 
According to drone docs, the `trigger` or `when` method can only support conditions like below:
```
trigger:
  branch:
    - feat/*
    - test/*
  event:
    - push
    - custom
```
But can we customize the trigger like feat/* branches triggered when pushing and test/* branched triggered when custom building?
Thanks.
