### ISSUE TITLE
`DRONE_RESOURCE_REQUEST_MEMORY` The setting does not take effect

### ISSUE THREAD

**Issue by guolong123** [harness/harness#3264]
I ran drone in K8s and set DRONE_RESOURCE_REQUEST_MEMORY to 1000MIB; but it didn't seem to work.
This is my runner configuration:
```yaml
# drone-runner-kube/values.yaml
...
env: 
  DRONE_NAMESPACE_DEFAULT: drone
  DRONE_RESOURCE_REQUEST_CPU: 500
  DRONE_RESOURCE_REQUEST_MEMORY: 1000MiB
...
```

It looks like its request configuration:
![image](https://user-images.githubusercontent.com/22833963/189838724-700ce82a-fa1d-4302-b306-3a90afc2a18d.png)
