### ISSUE TITLE
Error ':'

### ISSUE THREAD

**Issue by Powma** [harness/harness#3271]
Hello,

I trying to use Drone & Gitea with my docker-compose, but I have a problem... A erreur ":"
I will explain you how have this error but before I will show you my docker-compose file.

```yml
version: "3"

networks:
  gitea:
    external: false
  traefik:
    external: true

services:
  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
#    ports:
#      - 22:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
      - traefik
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.gitea.entrypoints=web, websecure
      - traefik.http.routers.gitea.rule=Host(`git.foo.fr`)
      - traefik.http.routers.gitea.tls=true
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.http.routers.gitea.tls.certresolver=production

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    labels:
      - traefik.enable=false

  drone:
    container_name: drone
    image: drone/drone:latest
    restart: unless-stopped
    depends_on:
      - gitea
    environment:
      # https://docs.drone.io/server/provider/gitea/
      - DRONE_GITEA_SERVER=https://git.foo.fr
      - DRONE_GITEA_CLIENT_ID=ac00a620-354e-4629-886e-8d4c7b635345
      - DRONE_GITEA_CLIENT_SECRET=gto_vzitdskyhzcp2a466natmvduatmtab7mrdmk5ereqnzjqhf2x73a
      - DRONE_RPC_SECRET=7c754a3ef8793b9fd8361c76789cc29c58ae6c0c
      - DRONE_SERVER_HOST=drone.foo.fr
      - DRONE_SERVER_PROTO=https
    networks:
      - traefik
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.drone.entrypoints=web, websecure
      - traefik.http.routers.drone.rule=Host(`drone.foo.fr`)
      - traefik.http.routers.drone.tls=true
      - traefik.http.services.drone.loadbalancer.server.port=80
      - traefik.http.routers.drone.tls.certresolver=production
```

First I begin with Gitea for generate an access OAuth with my account admin, and I past on my docker-compose file. The synchronisation work, but for login I have an error:

link : https://drone.foo.fr/login/error?message=:
![image](https://user-images.githubusercontent.com/15775304/194400628-12f3d42f-d34f-4872-9188-107298caf492.png)

On my log I can see that : 
```
drone    | {"level":"error","msg":"oauth: cannot exchange code: gta_sx3wu3uf3jyezqi26s7bax2clzfq34xmrnmrj5y3gd3n7yf2eq4a: : ","time":"2022-10-05T18:16:44Z"}
drone    | {"level":"debug","msg":"cannot authenticate user: : ","time":"2022-10-05T18:16:44Z"}
```

**Comment by OfficialBoyfriend** [comment]
I had the same problem when I was using Nginx to provide a reverse proxy for Gitea, and then I switched to Traefik and the problem went away.

I've attached the configuration I used, which may be useful to you.

Traefik:
```yml
version: "3.3"

services:
  traefik:
    image: "traefik:v2.0.0-rc3"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - TZ=Asia/Shanghai
```

Drone:
```yml
version: '3'

networks:
  internal:
    internal: true
  traefik_default:
    external: true

services:
  drone-server:
    image: drone/drone:2.13.0
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - DRONE_GITEA_SERVER=https://git.xxx.xxx
      - DRONE_GITEA_CLIENT_ID=1xxxxxxxxxxx
      - DRONE_GITEA_CLIENT_SECRET=gto_xxxxxxxxxxxxx
      - DRONE_SERVER_PROTO=https
      - DRONE_SERVER_HOST=ci.xxx.xxx
      - DRONE_NETWORK=cicd_default
      - DRONE_RUNNER_NETWORKS=cicd_default
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RPC_SECRET=Mxxxxxxxxxxxxxx
      - DRONE_AGENTS_ENABLED=true
    volumes:
      - ./data:/data
    networks:
      - internal
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.drone.entrypoints=web
      - traefik.http.routers.drone.rule=Host(`ci.xxx.xxx`)
      - traefik.http.services.drone.loadbalancer.server.port=80

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1.8.2
    restart: unless-stopped
    depends_on:
      - drone-server
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=Mxxxxxxxxxxxxxx
      - DRONE_RUNNER_CAPACITY=1
      - DRONE_RUNNER_NAME=drone-runner
      #- DRONE_RPC_SKIP_VERIFY=true
```

Gitea:
```yml
version: "3"

networks:
  internal:
    internal: true
  traefik_default:
    external: true

services:
  server:
    image: gitea/gitea:1.17.2
    environment:
      - TZ=Asia/Shanghai
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=xxxxxxxxx
    restart: unless-stopped
    networks:
      - internal
      - traefik_default
    volumes:
      - ./gitea:/data
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.gitea.entrypoints=web
      - traefik.http.routers.gitea.rule=Host(`git.xxx.xxx`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=xxxxxxxxx
      - POSTGRES_DB=gitea
    networks:
      - internal
    volumes:
      - ./postgres:/var/lib/postgresql/data
```
