### ISSUE TITLE
Support for custom action for the custom event trigger

### ISSUE THREAD

**Issue by turalf** [harness/harness#3305]
It would be very nice to have Drone's `custom` event type to support custom actions. 
E.g. 
If the trigger configuration is like this:
```yaml
kind: pipeline
type: kubernetes
name: custom-with-action
trigger:
  event:
    - custom
  action:
    - mycustomaction
```
the API call to trigger would look something like this.
`curl -X POST <drone-base-url>/api/repos/<org>/<repo>/builds?action=mycustomaction`
One use case would be to integrate Drone with an external CI system. Drone step would initiate a build on the other CI system that supports webhooks and when the other system finishes its job it makes the above POST request. Drone accepts that and looks at the action to choose a pipeline to run. You can currently do that without action, but if you have more than one custom trigger, all of them would be triggered.
