### ISSUE TITLE
Does `drone build` respect the notify setting?

### ISSUE THREAD

**Issue by amarnus** [harness/harness#331]
I'm using Drone `v0.2-0d25dc1`.

From a project directory, I did a `drone -v build`. I am not able to get a notification through any channel (tried email, Slack and webhook) although I can see the Docker container being built and my tests running (and passing).

```
...
Drone Build Results (1)
✓  (Less than a second)
```

This is how my `.drone.yml` file looks:

```
image: ubuntu
script:
 - bash script.sh
notify:
  webhook:
    on_success: true
    on_failure: true
    urls:
      - http://localhost:8080
```

Wasn't sure if I'm doing something wrong or the CLI just does not support this for now.
