### ISSUE TITLE
drone trigger paths 

### ISSUE THREAD

**Issue by hehua2018** [harness/harness#3360]
The directory update trigger does not take effect. There is no directory trigger code in the source code. Could you please fix it? Thank you.
```
kind: pipeline
type: docker
name: my-pipeline

steps:
  - name: checkout
    image: alpine/git
    commands:
      - ls  /tmp

trigger:
  paths:
   - hexiaoshi/
```
