### ISSUE TITLE
In the drone project, the build function is triggered based on a certain directory in the project.

### ISSUE THREAD

**Issue by hehua2018** [harness/harness#3361]
There is a build function in the drone project that triggers the build based on a certain directory in the project. If there is no such function, can you provide a trigger development document?
If the class is updated in the hexiaoshi directory, it will trigger the pipeline to execute build or deployment.
```
kind: pipeline
type: docker
name: my-pipeline

steps:
  - name: checkout
    image: alpine/git
    commands:
      - ls  /tmp

trigger:
  paths:
    - hexiaoshi/
```
