### ISSUE TITLE
when publish: swift set,  build fails,  no explanation.

### ISSUE THREAD

**Issue by paulczar** [harness/harness#344]
Here's my .drone.yml

```
image: paulczar/meez
env:
  - CI=drone
  - USE_SYSTEM_GECODE=1
script:
  - bundle install
  - bundle exec berks install
  - bundle exec rake spec style
  - bundle exec berks package /tmp/cookbook-master.tgz
publish:
  swift:
    username: paulczar
    password: {{rs_api_key}}
    auth_url: https://identity.api.rackspacecloud.com/v2.0
    region: DFW
    container: drone
    source: /tmp/cookbook-master.tgz
    target: cookbooks/cookbook-master.tgz
    branch: master
```

I have `rs_api_key` set as a param under the repository settings.

my drone logs

```
$ git clone --depth=50 --recursive --branch=master git://github.com/paulczar/cookbook-example.git /var/cache/drone/src/github.com/paulczar/cookbook-example
Cloning into '/var/cache/drone/src/github.com/paulczar/cookbook-example'...
perl: warning: Setting locale failed.
...
...
Running RuboCop...
Inspecting 11 files
...........

11 files inspected, no offenses detected
$ bundle exec berks package /tmp/dockercon-master.tgz
Cookbook(s) packaged to /tmp/dockercon-master.tgz
Swift: Publishing...
```
