### ISSUE TITLE
About Pipelines

### ISSUE THREAD

**Issue by zhaojing1987** [harness/harness#3542]
```
kind: pipeline
spec:
  stages:
  - type: ci
    spec:
      volumes:
      - name: dockersock
        spec: {}
        type: temp
      steps:
      - name: dind
        type: background
        spec:
          container:
            image: docker:dind
            privileged: true
          mount:
          - name: dockersock
            path: /var/run
  
      - name: test
        type: run
        spec:
          container: docker:dind
          mount:
          - name: dockersock
            path: /var/run
          script: |-
            sleep 5
            docker ps -a
```

I am testing the pipelines feature of Gitness, and while executing this example code, I encountered the following error:

![image](https://github.com/user-attachments/assets/a8a439ce-0a1a-4267-bd50-237fb12038bd)

I don't know how to handle the reason for the error.
