### ISSUE TITLE
Docker Artifact push failed

### ISSUE THREAD

**Issue by animeic** [harness/harness#3548]
Docker push keeps getting stuck in a loop, repeatedly pushing without success.

![1](https://github.com/user-attachments/assets/686054ec-4f3a-4e76-b238-6ec17d7273d5)

**Comment by pwolf-harness** [comment]
- What platform are you running this on?  
- What is the image you are trying to run?
- What Docker runtime are you using?
Is this still occurring?

**Comment by animeic** [comment]
root@C20240219104686:~# docker info
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: C20240219104686
 ID: 91c1b001-23cf-44a3-927d-f61e8ed91d57
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

My docker-compose.yml configuration file information：
```yml
services:
  gitness:
    image: harness/harness
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/harness/data:/data
    environment:
      GITNESS_HTTP_PORT: 3102
      GITNESS_ENCRYPTER_SECRET: 8b9df409e5eed9aef0f850166c6fec2d
      GITNESS_PRINCIPAL_ADMIN_EMAIL: example@gmail.com
      GITNESS_PRINCIPAL_ADMIN_PASSWORD: example
      GITNESS_USER_SIGNUP_ENABLED: false
      GITNESS_DATABASE_DRIVER: postgres
      GITNESS_DATABASE_DATASOURCE: "host=pg-db port=5432 sslmode=disable dbname=harness user=postgres password=example"
      GITNESS_HTTP_PROTO: https
      GITNESS_URL_BASE: https://repo.example.com
      GITNESS_URL_REGISTRY: https://repo.example.com
    ports:
      - 3102:3102
```
Any questions based on the above information? Thanks.

**Comment by animeic** [comment]
root@C20240219104686:~# docker info
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: C20240219104686
 ID: 91c1b001-23cf-44a3-927d-f61e8ed91d57
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

My docker-compose.yml configuration file information：
```yml
services:
  gitness:
    image: harness/harness
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/harness/data:/data
    environment:
      GITNESS_HTTP_PORT: 3102
      GITNESS_ENCRYPTER_SECRET: 8b9df409e5eed9aef0f850166c6fec2d
      GITNESS_PRINCIPAL_ADMIN_EMAIL: example@gmail.com
      GITNESS_PRINCIPAL_ADMIN_PASSWORD: example
      GITNESS_USER_SIGNUP_ENABLED: false
      GITNESS_DATABASE_DRIVER: postgres
      GITNESS_DATABASE_DATASOURCE: "host=pg-db port=5432 sslmode=disable dbname=harness user=postgres password=example"
      GITNESS_HTTP_PROTO: https
      GITNESS_URL_BASE: https://repo.example.com
      GITNESS_URL_REGISTRY: https://repo.example.com
    ports:
      - 3102:3102
```
Any questions based on the above information? Thanks.
