### ISSUE TITLE
pipline bug :  dind mount: permission denied (are you root?)

### ISSUE THREAD

**Issue by mouuii** [harness/harness#3581]
dind example  fail 
```
kind: pipeline
spec:
  stages:
  - type: ci
    spec:
      volumes:
      - name: dockersock
        spec: {}
        type: temp
      steps:
      - name: dind
        type: background
        spec:
          container:
            image: docker:dind
            privileged: true
          mount:
          - name: dockersock
            path: /var/run
  
      - name: test
        type: run
        spec:
          container: docker:dind
          mount:
          - name: dockersock
            path: /var/run
          script: |-
            sleep 5
            docker ps -a
```
![1731142552327](https://github.com/user-attachments/assets/583c582b-98da-4cf6-b928-b5ea94a5ae41)
