### ISSUE TITLE
The Visual Studio Code browser in Gitspaces failed to create

### ISSUE THREAD

**Issue by zyknow** [harness/harness#3594]
#### errorlog in Web
```
1 2024/12/2 22:42:12  Pulling image: mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04
2 2024/12/2 22:42:13  {"status":"Pulling from devcontainers/base","id":"dev-ubuntu-24.04"}
3 2024/12/2 22:42:13  {"status":"Digest: sha256:98575ffc6c65d3208a4f5856c2377668558d1dc01eb7e7fefdeb692532ebe85e"}
4 2024/12/2 22:42:13  {"status":"Status: Image is up to date for mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04"}
5 2024/12/2 22:42:13  Successfully pulled image
6 2024/12/2 22:42:13  Creating container: gitspace-harness-tradingviewnotice-rxq6b9
7 2024/12/2 22:42:14  Starting container: gitspace-harness-tradingviewnotice-rxq6b9
8 2024/12/2 22:42:14  Successfully started container
9 2024/12/2 22:42:14  Managing user output...
10 2024/12/2 22:42:14  Setting up user inside container
11 2024/12/2 22:42:14  Successfully setup user
12 2024/12/2 22:42:14  Setting up IDE inside container: vs_code_web
13 2024/12/2 22:42:16  Error while setting up IDE inside container: failed to copy media folder to container at path : error copying files to container: Error response from daemon: bad parameter: pathcannot be empty
```

#### errorlog in console
```
harness    | {"level":"error","error":"failed to resume start gitspace: couldn't call the agent start API: failed to start gitspace gitspace-harness-tradingviewnotice-rxq6b9: failed to setup IDE for gitspace gitspace-harness-tradingviewnotice-rxq6b9: failed to copy media folder to container at path : error copying files to container: Error response from daemon: bad parameter: pathcannot be empty","time":"2024-12-02T14:42:16.14165809Z","message":"error while handling gitspace infra event"}
```

#### docker-compose.yml
```
version: '3.9'
services:
  harness:
    image: harness/harness
    container_name: harness
    ports:
      - "31001:31000"
      - "31002:3022"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/_system/Docker/Harness/data:/data
    environment:
      - GITNESS_DATABASE_DRIVER=postgres
      - GITNESS_DATABASE_DATASOURCE=*
      - GITNESS_PRINCIPAL_ADMIN_EMAIL=*@qq.com
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=*
      - GITNESS_HTTP_PORT=31000
      - GITNESS_URL_BASE=https://*:31000

      - GITNESS_URL_UI=https://*:31000
      # - GITNESS_URL_API=https://*:31000/api
      - GITNESS_URL_CONTAINER=https://*:31000
      - GITNESS_URL_GIT=https://*:31000/git
      - GITNESS_URL_REGISTRY=https://*:31000
      - GITNESS_URL_GIT_SSH=ssh://*:31002


      - GITNESS_HTTP_PROTO=https
      - GITNESS_URL_INTERNAL=https://*:31000
      - GITNESS_SSH_PORT=31002
      #- HTTP_PROXY=192.168.0.1:7893
      #- HTTPS_PROXY=192.168.0.1:7893
```
