### ISSUE TITLE
Bug: Cannot connect to the Docker daemon in last updated plugins/docker

### ISSUE THREAD

**Issue by AGPDev** [harness/harness#3607]
I've been using Gitness for months and haven't had any problems. Since yesterday this error started occurring. I noticed that the plugin was updated and I can't solve it.

#### **`Last run with error`**

![image](https://github.com/user-attachments/assets/d7d34135-83a5-4cde-816f-b741d5a55bf5)

#### **`Last run successfully`**

![image](https://github.com/user-attachments/assets/c3cece30-e97b-465d-9e3e-0eba78be1aaf)

#### **`docker-compose.yml`**
```yml
services:
  gitness:
    image: harness/harness:3.0.1
    container_name: gitness
    privileged: true
    restart: always
    environment:
      GITNESS_DATABASE_DRIVER: "postgres"
      GITNESS_DATABASE_DATASOURCE: "host=postgres port=5432 sslmode=disable dbname=gitness user=$DB_USER password=$DB_PASSWORD"
      GITNESS_PRINCIPAL_ADMIN_EMAIL: "**********"
      GITNESS_URL_BASE: ""**********"
      GITNESS_USER_SIGNUP_ENABLED: "false"
      GITNESS_CI_PARALLEL_WORKERS: 3
      GITNESS_URL_REGISTRY: ""**********"
    networks:
      - public
    ports:
      - 3000:3000
      - 3022:3022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .data:/data

networks:
  public:
    external: true
```
