### ISSUE TITLE
Stage '' not found in build file : resource not found when drone exec type exec?

### ISSUE THREAD

**Issue by taadis** [harness/harness#3611]
Hi, Use only drone-cli in local from doc https://docs.drone.io/quickstart/cli/

install drone-cli

```
brew install drone-cli
```

Use the following .drone.yml:

```
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
```

run is ok

```
drone exec
```

But got failed when update type: exec

```
kind: pipeline
type: exec # just update
name: default

steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
```

got failed

```
Stage '' not found in build file : resource not found
exit status 1
```

How to determine what resource are missing? Or what should be done?
