### ISSUE TITLE
How to pass arguments to plugin?

### ISSUE THREAD

**Issue by kesavkolla** [harness/harness#3632]
I have a docker image which has entrypoint to my main program. The main program take CLI arguments. How do I pass the CLI arguments in step type plugin.

When I run my docker using docker run imagename arg1 arg2 it works.

I am trying to do this in the pipeline:

```yaml
- step:
    type: Plugin
    name:  my plugin
    identifier: update_jira
    spec:
      connectorRef: org.nexusharnessplatform
      image: [docker.xenial.com:18444/harness-custom-steps:harness](http://docker.xenial.com:18444/harness-custom-steps:harness)
      args:
      - arg1
      - arg2
```

The `args` is not working.

How do we pass args to the entrypoint ?
