### ISSUE TITLE
Branch based deploys

### ISSUE THREAD

**Issue by joejwright** [harness/harness#383]
It would be nice to be able to have different deploy options based on git branch. I would imagine the drone.yml would look something like this:

```
deploy:
  staging:
    heroku:
      app: safe-island-6261-staging
  master:
    heroku:
      app: safe-island-6261-staging
```

We generally don't deploy our development branch (used for local testing only), but deploy both our staging and master branches.
