### ISSUE TITLE
kubernetes/fleet support

### ISSUE THREAD

**Issue by blairham** [harness/harness#455]
It would be really nice to be able to send a build to kubernetes/fleet and have a nice cluster behind the build farm. 

Currently I have a CoreOS cluster that is hosting the drone as a docker, I would love to be able to use that same cluster through kubernetes or fleet to have the builds run in, instead of a docker inside my docker container.

If that isn't on the radar at least being able to farm it off to a different docker would be ideal (if it already isn't through environment variables).

**Comment by sebv** [comment]
+1 It would be much easier to talk to the kubernetes rest api to create workers.

**Comment by sebv** [comment]
For instance you just need to post  a container pod definition (see below)  to the master and the container will start on any free node in the cluster:

```
apiVersion: v1
kind: Pod
metadata:
  name: test_123
  labels:
spec:
  containers:
  - name: test_123
    image: library/java:openjdk-8
    env:
       - name: DRONE_SERVER
       - value: <drone server host>
    command: "<whatever needed to kick of the tests>"
```
