### ISSUE TITLE
Private Parameters Injection Lazy Behavior

### ISSUE THREAD

**Issue by itomaldonado** [harness/harness#692]
While testing Private Parameters during build I came across an interesting behavior . During variable injection it seems that it is using a _lazy_ match. 

**I was wondering if this was a bug or intended?**

For example (Look at the **registry_login_url** entry):

A drone.yml file with:

```
...
docker:
        dockerfile: Dockerfile
        image_name: $$username/wsapp
        docker_host: $$docker_host
        docker_version: $$docker_version
        registry_login_url: $$registry_login_url
        registry_login: $$registry_login
        username: $$username
        password: $$password
        email: $$email
        keep_builds: false
        tag: 0.1
        branch: master
...
```

And the Private Params contain: 

```
...
username: someUser
password: somePassword
email: someEmail@email.email
docker_host: tcp://0.0.0.0:2375
docker_version: 1.3.0
registry_login: true
registry_login_url: https://registry.hub.docker.com/v1/
...
```

The above will then be injected in the drone.yml as:

```
...
docker:
        dockerfile: Dockerfile
        image_name: someUser/someregistry
        docker_host: tcp://0.0.0.0:2375
        docker_version: 1.3.0
        registry_login_url: true_url
        registry_login: true
        username: someUser
        password: somePassword
        email: someEmail@email.email
        keep_builds: false
        tag: 0.1
        branch: master
...
```

As you can see the **registry_login** entry is a subset of **registry_login_url** and it is contained within the beginning of that entry, so when the Params are injected, the **registry_login** entry value will be inserted into **registry_login_url** thus creating **true_url**... I haven't tested other scenarios.
