### ISSUE TITLE
Deploy to multiple targets of the same 

### ISSUE THREAD

**Issue by gust1n** [harness/harness#699]
We're deploying via git using the new when: branch:master but would like to deploy via git to other endpoints for other branches. I could not find any documentation and looking at the code it seems like there could be only one deploy target per service. We're using the following code:

```
deploy:
    git:
    target: OMITTED
    branch: master
    force: false
    when:
        branch: master
```

and would like something like:

```
deploy:
    git:
    target: A DIFFERENT OMITTED
    branch: develop
    force: false
    when:
        branch: develop
```

for the same project. Is this possible?
