### ISSUE TITLE
Loading a custom dockerfile for image?

### ISSUE THREAD

**Issue by Tombert** [harness/harness#723]
Can this be achieved?  Can this be specified in the drone.yml?

**Comment by fabiosussetto** [comment]
@bradrydzewski any thoughts about supporting this in 0.5? See this mini discussion about it on gitter: https://gitter.im/drone/drone?at=57ec2dd2857ab70f7d4c9eb3 
Event just your opinion on this would be good to have. 
Thanks.

**Comment by bradrydzewski** [comment]
We aren't adding any major new features to 0.5 to avoid prolonging the release, but can consider options for 0.6 or later. Specifically supporting the docker-compose build block [1], which drone can already parse but currently ignores.

[1] https://docs.docker.com/compose/compose-file/#/build

**Comment by ViViDboarder** [comment]
Any chance of this being considered now?

My example use case is building Android applications. I can try to cache as many files as I can, but it would be easier to have docker manage the layer caching for me and to maintain a Dockerfile of my build environment instead of an image.

**Comment by bradrydzewski** [comment]
> Any chance of this being considered now?

this is being tracked at https://github.com/drone/drone/issues/1609#issuecomment-304986851

> My example use case is building Android applications. I can try to cache as many files as I can, but it would be easier to have docker manage the layer caching for me and to maintain a Dockerfile of my build environment instead of an image.

note that you can always work directly with the host machine docker daemon today, without any required changes to drone, by mounting the host machine docker socket

```yaml
pipeline:
  setup:
    image: docker
    commands:
      - docker build -t -i android  ... # build the image here
      - docker push ... # optionally push to dockerhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build:
    image: android # use the image here
    commands:
      - ....
```
